### ISSUE TITLE
Android implementation sync files with gradle files fails

### ISSUE THREAD

**Issue by TheWygoda** [Synerise/react-native-synerise-sdk#2]
I'm facing the issue with android implementation. 

Issue I've run into is with syncing project with gradle files.

react-native: 61.5

buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 29
targetSdkVersion = 29
supportLibVersion = "28.0.0"
 kotlinVersion = '1.3.41'

<img width="1130" alt="synerise gradle issue" src="https://user-images.githubusercontent.com/32249347/101291652-c328ee00-380a-11eb-9436-5b0dc454dc52.png">

By the way, documentation might lacks a note of 
`import com.synerise.sdk.react.RNSyneriseSdkPackage;` in MainApplication.java ;)

**Comment by konned** [comment]
I think you lack : 
`maven {
   url "https://synerise.bintray.com/Android"
}` in your root  build.gradle file. 
We are support android sdk version from API 21. 
Imports are suggested by IDE. You are probably not using android studio that's why it was not suggested. I will add it.
For more information please check: https://help.synerise.com/developers/react-native-sdk/installation-and-configuration/

**Comment by TheWygoda** [comment]
Sweet! Problem solved, thank you!
